#requires -Version 5.1
<#
.SYNOPSIS
按 src/bundle.conf 把多个 Lua 文件合并成单个 dist/app.lua。

.DESCRIPTION
设备运行时没有 require/load，多文件开发必须合并成单文件后上传。
合并顺序 = bundle.conf 的行顺序；模块文件里不能写 return。
输出固定为 UTF-8 无 BOM、LF 换行，避免设备端 Lua 解析问题。
#>
[CmdletBinding()]
param(
    [string]$Conf = 'src\bundle.conf',
    [string]$Out = 'dist\app.lua'
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$confPath = Join-Path $root $Conf
$outPath = Join-Path $root $Out

if (-not (Test-Path -LiteralPath $confPath)) {
    throw "找不到合并清单: $confPath"
}

$utf8 = New-Object System.Text.UTF8Encoding($false)
$baseDir = Split-Path -Parent $confPath
$entries = @()
foreach ($line in [System.IO.File]::ReadAllLines($confPath, $utf8)) {
    $t = $line.Trim()
    if ($t -eq '' -or $t.StartsWith('#')) { continue }
    $entries += $t
}
if ($entries.Count -eq 0) {
    throw "合并清单是空的: $confPath"
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.Append("-- generated by tools/build.ps1 -- 不要手改，改 src/ 后重新构建`n")
[void]$sb.Append("-- bundle: " + ($entries -join ', ') + "`n`n")

foreach ($entry in $entries) {
    $file = Join-Path $baseDir $entry
    if (-not (Test-Path -LiteralPath $file)) {
        throw "bundle.conf 列出的文件不存在: $Conf -> $entry"
    }
    $text = [System.IO.File]::ReadAllText($file, $utf8)
    $text = $text.Replace("`r`n", "`n").Replace("`r", "`n")
    [void]$sb.Append("-- >>> $entry`n")
    [void]$sb.Append($text)
    if (-not $text.EndsWith("`n")) { [void]$sb.Append("`n") }
    [void]$sb.Append("`n")
}

$dir = Split-Path -Parent $outPath
if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $utf8)

$bytes = $utf8.GetByteCount($sb.ToString())
Write-Host ("[build] {0} -> {1} ({2} bytes)" -f ($entries -join ' + '), $Out, $bytes)
